Added Publish support and General refactor
dbarenholz/halcyon-obsidian pull request #11
Opened 2024-05-04 04:12 UTC by sigrunixia

Lets fix this thing up!

2024-05-09 11:37 UTC, dbarenholz commented
Hi Sig!

Can you please split this up into the following PRs? 

1. Addition of publish support. Also think about modifying the build script so it automatically builds when running `npm run build`.
2. Addition of stylelint, so that I can modify whatever stylelint wants, if desired. 
3. _After_ (2) is merged: the refactor (potentially - I still have a hard time looking at the 3000+ lines changed). 

Thank you!

2024-05-09 11:42 UTC, dbarenholz commented
Also: any reason to bump the obsidian version? Is the theme not compatible with 1.0.0 anymore?

2024-05-09 15:31 UTC, sigrunixia commented
> Also: any reason to bump the obsidian version? Is the theme not compatible with 1.0.0 anymore?

We're going to be updating the sample templates to start at 1.5., so doing this for parity.

2024-05-09 21:00 UTC, dbarenholz commented
> > Also: any reason to bump the obsidian version? Is the theme not compatible with 1.0.0 anymore?
> 
> We're going to be updating the sample templates to start at 1.5., so doing this for parity.

https://docs.obsidian.md/Plugins/User+interface/Right-to-left it appears we'll have to put it at 1.6 and make it RTL compatible :)

2024-05-11 17:09 UTC, sigrunixia commented
If I recall correctly, we actually do not have any of the "faults" in Halcyon.

2024-05-11 17:13 UTC, sigrunixia commented
I also suggest we do a gentle refactor first. If Publish goes first, I'd have to redo the work again.

Here is what ebullient and I did for splitting the files up into Publish and not-publish. Would this work for you?

https://github.com/ebullient/obsidian-theme-ebullientworks/tree/main/src/fragments

2024-05-12 12:02 UTC, dbarenholz commented
> I also suggest we do a gentle refactor first. If Publish goes first, I'd have to redo the work again.
> 
> Here is what ebullient and I did for splitting the files up into Publish and not-publish. Would this work for you?
> 
> https://github.com/ebullient/obsidian-theme-ebullientworks/tree/main/src/fragments

The idea: yes.
The implementation of the idea (so a single `fragments` folder, and all files being dumped in there): no.

I want to keep separate files according to the documentation as listed in <https://docs.obsidian.md/Reference/CSS+variables/CSS+variables>.

I'm happy to refactor first; does the fragment-idea work while keeping separate files according to the link above?

2024-05-12 12:21 UTC, dbarenholz requested changes
Gitub can now show me an actually diff (as opposed to "file is deleted") so I can properly review.

Some notes:
1. I'd like to keep variables in the same order as the documentation. Even if that means that there are used variables, some unused variables, and then more used variables. I find it easier to reference back to the docs if they're in the same order.
2. I like that you simplify selectors, and use scss magic where applicable.
3. I've noticed a few instances where you modified things -- can you comment on why this is done?

2024-05-12 12:21 UTC, dbarenholz commented on scss/editor/_headings.scss
> -	--h6-weight: 575;
I would like to keep these in order as they appear in the documentation: https://docs.obsidian.md/Reference/CSS+variables/Editor/Headings

I see that there's new variables, but that's for a different PR.

2024-05-12 12:21 UTC, dbarenholz commented on scss/editor/_horizontal-rule.scss
> -		// --hr-thickness: ;;
I'd like to keep these in the same order as the documentation. Please don't remove them, even if they're unused.

2024-05-12 12:21 UTC, dbarenholz commented on scss/editor/_link.scss
> -	--link-external-color-hover: var(--halcyon-palette-lilac-hover);
I'd like to keep these in the same order as the documentation.

2024-05-12 12:21 UTC, dbarenholz commented on scss/editor/_properties.scss
> -	--metadata-label-text-color-hover: var(--halcyon-palette-cyan-hover);
I'd like to keep these in the same order as the documentation.

2024-05-12 12:21 UTC, dbarenholz commented on scss/components/_tabs.scss
> +  --tab-outline-color: var(--halcyon-accent);
Is there a reason why this is no longer commented?

2024-05-12 12:21 UTC, dbarenholz commented on scss/components/_toggle.scss
> +	--toggle-radius: 0px;
Is there a reason why this is no longer commented?

2024-05-12 12:21 UTC, dbarenholz commented on scss/core-plugins/_file-explorer.scss
> -	// --vault-name-font-weight: ;
I'd like to keep these in the same order as the documentation.

2024-05-12 12:21 UTC, dbarenholz commented on scss/core-plugins/_graph.scss
> -	--graph-node-tag: var(--halcyon-palette-lilac);
I'd like to keep these in the same order as the documentation.

2024-05-12 12:21 UTC, dbarenholz commented on scss/core-plugins/_search.scss
> +	--search-icon-size: 10px;
Is there a reason why this is no longer commented?

2024-05-12 12:21 UTC, dbarenholz commented on scss/core-plugins/_search.scss
> -	// --search-icon-size: 10px;
I'd like to keep these in the same order as the documentation.

2024-05-12 12:21 UTC, dbarenholz commented on scss/editor/_blockquote.scss
> +	--callout-padding: var(--size-4-3) var(--size-4-6);
I believe this `--callout-padding` should not be here.

2024-05-12 12:21 UTC, dbarenholz commented on scss/editor/_callout.scss
> -	--callout-padding: var(--size-4-3) var(--size-4-6);
I'd like to keep these in the same order as the documentation.

2024-05-12 12:21 UTC, dbarenholz commented on scss/editor/_callout.scss
> +	}
I understand the rewrite for `.theme-dark body {}`, but why the rest?

Also: there is an empty `.callout` block, is this intended?

2024-05-12 12:21 UTC, dbarenholz commented on scss/editor/_code.scss
> -	// --code-size
I'd like to keep these in the same order as the documentation.

2024-05-12 12:21 UTC, dbarenholz commented on scss/editor/_lists.scss
> -	// --list-spacing: ;
I'd like to keep these in the same order as the documentation.

2024-05-12 12:21 UTC, dbarenholz commented on scss/editor/_table.scss
> -	--table-header-size: larger;
I'd like to keep these in the same order as the documentation.

2024-05-12 12:21 UTC, dbarenholz commented on scss/editor/_tags.scss
> -	);
I'd like to keep these in the same order as the documentation.

2024-05-12 12:21 UTC, dbarenholz commented on scss/extra/_fix-border-radius.scss
Very nice, thanks for the scss magic!

2024-05-12 12:21 UTC, dbarenholz commented on scss/plugins/_dataview.scss
> +//
nitpick: For multiline comments I personally prefer the `/* */` style.

2024-05-12 12:21 UTC, dbarenholz commented on scss/plugins/_highlightr-plugin.scss
> +  //  for the various highlighting styles that the plugin provides.
nitpick: For multiline comments I personally prefer the `/* */` style.

2024-05-12 12:21 UTC, dbarenholz commented on scss/plugins/_obsidian-dynamic-highlights.scss
> +// Dynamic Highlights (by sailKite)
nitpick: For multiline comments I prefer the `/* */` style.

2024-05-12 12:21 UTC, dbarenholz commented on scss/plugins/_obsidian-dynamic-highlights.scss
> +    }
Very nice, much more readable.

2024-05-12 12:21 UTC, dbarenholz commented on scss/window/_ribbon.scss
> -	// --ribbon-background: ;
I'd like to keep these in the same order as the documentation.

2024-05-12 12:21 UTC, dbarenholz commented on scss/window/_window-frame.scss
> -	// --titlebar-border-width:
I'd like to keep these in the same order as the documentation.

2024-05-12 12:24 UTC, dbarenholz commented
@sigrunixia Many comments in the review are effectively "please move a line up or down" -- there's only like 3 instances that require thought.

2024-10-02 21:51 UTC, sigrunixia commented
Closing to resubmit, because editing existing PR when your branch is gone is annoying.

2024-10-02 21:51 UTC, closed without merging